project/blueprints/cart/models.py
from project import db, login
from datetime import datetime

class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    datecreated = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    cart_items = db.relationship('CartItem', backref='cart', lazy=True)

    def __repr__(self):
        return f"<Cart|ID: {self.id}, User: {self.user_id}>"

class CartItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    cart_id = db.Column(db.Integer, db.ForeignKey('cart.id'), nullable=False)
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'), nullable=False)
    quantity = db.Column(db.Integer, nullable=False, default=1)
    date_added = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    product = db.relationship('Product', backref='cartitem', lazy=True)

    def __repr__(self):
        return f"<CartItem|ID: {self.id}, Cart: {self.cart_id}, Product: {self.product_id}, Quantity: {self.quantity}>"

project/blueprints/products/models.py
from project import db, login
from datetime import datetime

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    price = db.Column(db.Numeric(5, 2), nullable=False)
    image_url = db.Column(db.String(255))
    date_created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    category_id = db.Column(db.Integer, db.ForeignKey("category.id"), nullable=False)

    def __repr__(self):
        return f"<Product|{self.name}>"
    
    def save(self):
        db.session.commit()
    
    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def create(self):
        db.session.add(self)
        db.session.commit()
    
    def to_dict(self):
        return {
            'id': self.id,
            'prod_name': self.name,
            'price': self.price,
            'image': self.image_url,
            'date_created': self.date_created,
            'category_id': self.category_id
        }
    
    def update(self, data):
        for field in data:
            if field not in {'name', 'price', 'image_url', 'category_id'}:
                continue
            setattr(self, field, data[field])
        db.session.commit()

class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    color = db.Column(db.String(20), nullable=False)
    date_created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    products = db.relationship("Product", backref="category")

    def __repr__(self):
        return f"<Category|{self.name}>"
    

project/blueprints/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired

class ProductUpdate(FlaskForm):
    name = StringField('Product Name', validators=[DataRequired()])
    image_url = StringField('Image URL', validators=[DataRequired()])
    price = StringField('Price', validators=[DataRequired()])
    category = SelectField('Category')
    submit = SubmitField('Update Product')
    create = SubmitField('Create Product')

project/blueprints/cart/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from project import db
from flask_login import login_required, current_user
from .models import Cart, CartItem
from project.blueprints.products.models import Product

cart = Blueprint('cart', __name__)

# Route to add products to cart
@cart.route('/add_to_cart/<int:prod_id>')
@login_required
def add_to_cart(prod_id):
    product = Product.query.get(prod_id)
    if product:
        cart = Cart.query.filter_by(user_id=current_user.id).first()
        if not cart:
            cart = Cart(user_id=current_user.id)
            db.session.add(cart)
            db.session.commit()
        
        # Check if the product is already in the cart
        cart_item = CartItem.query.filter_by(cart_id=cart.id, product_id=product.id).first()

        if cart_item:
            # If the product is already in the cart, update the quantity
            cart_item.quantity += 1
            flash('Quantity updated in the cart successfully!', 'success')
        else:
            # If the product is not in the cart, add a new item
            cart_item = CartItem(cart_id=cart.id, product_id=product.id)
            db.session.add(cart_item)
            flash('Product added to the cart successfully!', 'success')

        db.session.commit()
    else:
        flash('Product not found!', 'danger')

    return redirect(url_for('main.index'))

# Route to view cart
@cart.route('/view_cart')
@login_required
def view_cart():
    # Implement a route to display the contents of the cart
    cart = Cart.query.filter_by(user_id=current_user.id).first()
    if cart:
        cart_items = CartItem.query.filter_by(cart_id=cart.id).all()
        return render_template('cart.html', cart=cart, cart_items=cart_items)
    else:
        flash('Cart is empty!', 'info')
        return render_template('cart.html', cart=None, cart_items=None)

project/blueprints/products/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import ProductUpdate
from flask_login import login_required, current_user
from .models import Product, Category

products = Blueprint('products', __name__)

@products.route('/product')
@login_required
def product():
    return 'Hello!'

@products.route('/product/<prod_id>')
def product_info(prod_id):
    product = Product.query.get_or_404(prod_id)
    return render_template('product.html', product=product)

@products.route('/product/<prod_id>/edit', methods=['GET', 'POST'])
@login_required
def product_edit(prod_id):
    form = ProductUpdate()
    form.category.choices = [(c.id, c.name) for c in Category.query.all()]
    product = Product.query.get_or_404(prod_id)
    if form.validate_on_submit():
        if not current_user.is_admin:
            flash("You don't have permissions to do that.", "danger")
            return redirect(url_for('main.index'))
        name = form.name.data
        image_url = form.image_url.data
        price = form.price.data
        category = form.category.data

        product.name = name
        product.image_url = image_url
        product.price = price
        product.category_id = category

        product.save()
        flash(f'Successfully Updated { product.name }!', 'success')
        return redirect(url_for('products.product_edit', prod_id=prod_id))

    return render_template('edit_product.html', product=product, form=form)

@products.route('/product/create', methods=['GET', 'POST'])
@login_required
def new_product():
    form = ProductUpdate()
    form.category.choices = [(c.id, c.name) for c in Category.query.all()]
    if not current_user.is_admin:
        flash("You don't have permissions to do that.", "danger")
        return redirect(url_for('main.index'))
    if form.validate_on_submit():
        name = form.name.data
        price = form.price.data
        image_url = form.image_url.data
        category = form.category.data

        new_product = Product()
        new_product.name = name
        new_product.price = price
        new_product.image_url = image_url
        new_product.category_id = category

        new_product.create()

        flash(f'{new_product.name} has been created successfully!', 'success')
        return redirect(url_for('products.product_info', prod_id=new_product.id))



    return render_template('new_product.html', form=form)

@products.route('/product/<prod_id>/delete')
@login_required
def delete_product(prod_id):
    if not current_user.is_admin:
        flash("You don't have permissions to do that.", "danger")
        return redirect(url_for('main.index'))
    product = Product.query.get_or_404(prod_id)
    product.delete()
    flash(f'{product.name} has been deleted', 'danger')
    return redirect(url_for('main.index'))

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="Description" content="Enter your description here"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
        <link rel="stylesheet" href="../static/styles/style.css">
        {% block title %} <title>Home</title> {% endblock %}
    </head>
    <body>
        {% include 'nav.html' %}

        {% block image %}
        {% endblock %}

        <div class="container">
            {% include 'messages.html' %}
            {% block content %}
    
            {% endblock %}
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
    </body>
</html>

project/templates/cart.html
{% block title %} <title>Cart</title> {% endblock %}
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">Shopping Cart</h1>
{% if cart %}
    <h3>User: {{ current_user.username }}</h3>
    <ul>
        {% for item in cart_items %}
            <li>{{ item.product.name}} - Quantity: {{ item.quantity }}</li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Cart is empty.</p>
{% endif %}
<a href="{{ url_for('main.index') }}">Back to Products</a>
{% endblock %}

project/templates/edit_product.html
{% extends "base.html" %}

{% block content %}
<h1 class="d-flex justify-content-center m-5">Update Product</h1>
<!-- Product card -->
<div class="row d-flex justify-content-center">
    <div class="col-12 col-sm-6 col-md-4">
        <div class="card">
            <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
            <!-- style="width: 300px; height: 337px; object-fit: cover;" -->
            <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">${{ product.price }}</p>
            <p class="card-text">{{ product.category.name }}</p>
            </div>
        </div>
    </div>
    <!-- Update product form -->
    <div class="col-12 col-sm-6 col-md-4 text-center">
            <form action="" method="post">
                {{ form.csrf_token }}
                <div class="form-group">
                    <div class="col-12 mb-3">
                        {{ form.name.label }}
                        <fieldset class="w-75 mx-auto d-flex justify-content-center align-items-center">
                            {{ form.name(class='form-control', placeholder='Product name', value=product.name) }}
                        </fieldset>
                    </div>
                    <div class="col-12 mb-3">
                        {{ form.image_url.label }}
                        <fieldset class="w-75 mx-auto d-flex justify-content-center align-items-center">
                            {{ form.image_url(class='form-control', placeholder='image_url', value=product.image_url) }}
                        </fieldset>
                    </div>
                    <div class="col-12 mb-3">
                        {{ form.price.label }}
                        <fieldset class="w-75 mx-auto d-flex justify-content-center align-items-center">
                            {{ form.price(class='form-control', placeholder='Price', value=product.price) }}
                        </fieldset>
                    </div>
                    <div class="col-12 mb-3">
                        {{ form.category.label }}
                        <fieldset class="w-75 mx-auto d-flex justify-content-center align-items-center">
                            <select class="form-control" name="category">
                                {% for category in form.category.choices %}
                                    {% if category[0] == product.category_id %}
                                        <option value="{{ category[0] }}" selected>{{ category[1] }}</option>
                                    {% else %}
                                        <option value="{{ category[0] }}">{{ category[1] }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </fieldset>
                    </div>


                    <div class="col-12 text-center mb-3">
                        {{ form.submit(class='btn btn-primary w-50') }}
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger w-25" data-bs-toggle="modal" data-bs-target="#deleteModal">
                            Delete
                        </button>
                        
                        <!-- Modal -->
                        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Delete Item?</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                This action cannot be undone. Are you sure you want to delete {{ product.name }}?
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <a href="{{ url_for('products.delete_product', prod_id=product.id) }}" class="btn btn-danger">Yes, Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

project/templates/index.html
{% extends 'base.html' %}

{% block content %}
{% if current_user.is_authenticated %}
    <h1 class="text-center mt-3">Welcome back, {{ current_user.username.capitalize() }}!</h1>
{% else %}
    <h1 class="text-center mt-3">Please Register or Login!</h1>
{% endif %}
<!-- Playing Cards -->
<h1 class="text-center m-5">Card Games</h1>
<div class="row">
{% for product in products %}
    {% if product.category_id == 1 %}
        <div class="col-12 col-sm-6 col-md-4 mb-3">
            <div class="card">
                <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
                <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">${{ product.price }}</p>
                <a href="{{ url_for('products.product_info', prod_id=product.id) }}" class="btn btn-primary">More Info</a>
                <a href="{{ url_for('products.product_edit', prod_id=product.id) }}" class="btn btn-secondary">Edit</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}
</div>
<!-- Board Games -->
<!-- To my love Sherley <3 -->
<h1 class="text-center m-5">Board Games</h1>
<div class="row">
{% for product in products %}
    {% if product.category_id == 2 %}
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
                <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
                <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">${{ product.price }}</p>
                <a href="{{ url_for('products.product_info', prod_id=product.id) }}" class="btn btn-primary">More Info</a>
                <a href="{{ url_for('products.product_edit', prod_id=product.id) }}" class="btn btn-secondary">Edit</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}
</div>

{% endblock %}

project/templates/login.html
{% block title %} <title>Login</title> {% endblock %}

{% extends 'base.html' %}
{% block content %}
<h1 class="d-flex justify-content-center m-5">login</h1>
<form action="" method="post">
    {{ form.csrf_token }}
    <div class="form-group d-flex justify-content-center">
        <div class="col-10 col-md-4 col-sm-6 mb-3">
            <fieldset class="">
                {{ form.username.label }}
                {{ form.username(class='form-control', placeholder='Username') }}
            </fieldset>
        </div>
    </div>
    <div class="form-group d-flex justify-content-center">
        <div class="col-10 col-md-4 col-sm-6 mb-3">
            <fieldset class="">
                {{ form.password.label }}
                {{ form.password(class='form-control', placeholder='Password') }}
            </fieldset>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="col-10 col-md-4 col-sm-6">
            {{ form.submit(class='btn btn-outline-primary w-100') }}
        </div>
    </div>
</form>

<div class="row">
    <div class="d-flex justify-content-center mt-4">
        Don't have an account? <a href="{{ url_for('auth.register') }}" class="ms-2 me-2">Sign up</a>
    </div>
</div>
{% endblock %}

project/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

project/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
	<div class="container-fluid">
		<a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
	  	</button>
	  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				{% if current_user.is_anonymous %}
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
				</li>
				{% else %}

				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						{{ current_user.username.capitalize() }}
					</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><a class="dropdown-item" href="{{ url_for('auth.profile', username=current_user.username) }}">Profile</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
					</ul>
				</li>
				{% endif %}
				{% if current_user.is_admin %}
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('products.new_product') }}">Create product</a>
				</li>
				{% endif %}
				<li class="nav-item">
					<a href="{{ url_for('cart.view_cart') }}" class="nav-link bi bi-cart"> Cart</a>
				</li>
			</ul>
			<form class="d-flex">
				<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-primary" type="submit">Search</button>
			</form>
		</div>
	</div>
</nav>

<style>
	/* CSS Reset */
	* {
		margin: 0;
		padding: 0;
		box-sizing: border-box;
	}

	body {
		font-family: Arial, sans-serif;
	}

</style>

project/templates/new_product.html
{% block title %} <title>New Product</title> {% endblock %}
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center m-5">Create New Product</h1>
<div class="col-12 text-center">
    <form action="" method="post">
        {{ form.csrf_token }}
        <div class="form-group">
            <div class="col-12 mb-3">
                {{ form.name.label }}
                <fieldset class="w-50 mx-auto d-flex justify-content-center align-items-center">
                    {{ form.name(class='form-control', placeholder='Product name', value=name) }}
                </fieldset>
            </div>
            <div class="col-12 mb-3">
                {{ form.image_url.label }}
                <fieldset class="w-50 mx-auto d-flex justify-content-center align-items-center">
                    {{ form.image_url(class='form-control', placeholder='image_url', value=image_url) }}
                </fieldset>
            </div>
            <div class="col-12 mb-3">
                {{ form.price.label }}
                <fieldset class="w-50 mx-auto d-flex justify-content-center align-items-center">
                    {{ form.price(class='form-control', placeholder='Price', value=price) }}
                </fieldset>
            </div>
            <div class="col-12 mb-3">
                {{ form.category.label }}
                <fieldset class="w-50 mx-auto d-flex justify-content-center align-items-center">
                    <select class="form-control" name="category">
                        {% for category in form.category.choices %}
                            {% if category[0] == category_id %}
                                <option value="{{ category[0] }}" selected>{{ category[1] }}</option>
                            {% else %}
                                <option value="{{ category[0] }}">{{ category[1] }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </fieldset>
            </div>
            {{ form.create(class='btn btn-outline-primary w-50') }}
        </div>
    </form>
</div>
{% endblock %}

project/templates/plans.html
{% block title %} <title>Plans</title> {% endblock %}
{% extends 'base.html' %}

{% block content %}
<div class="row d-flex justify-content-center m-5">
    <div class="col-12 col-md-8 border">
        <h1 class="text-center">Select Plan</h1>
    </div>
</div>
<div class="row d-flex justify-content-center m-3">
    <div class="col-12 col-md-4 d-flex justify-content-start">
        <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
          <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
          <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-4 d-flex justify-content-end m-1">
        <h1 class="text-center">Total Price</h1>
    </div>
</div>
<div class="row d-flex justify-content-center">
    <div class="col-12 col-md-4">
        <button class="btn btn-primary w-100" type="button">Select this plan</button>
    </div>
</div>
{% endblock %}

project/templates/product.html
{% block title %} <title>{{ product.name }}</title> {% endblock %}
{% extends 'base.html' %}

{% block content %}
<div class="row mt-5">
    <!-- Display Product -->
    <!-- <div class="col-2">
        <img src="{{ product.image_url }}" class="img-thumbnail rounded mx-auto d-block" alt="">
        <img src="{{ product.image_url }}" class="img-thumbnail rounded mx-auto d-block" alt="">
    </div> -->
    <div class="col-lg-6 col-md-3">
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{{ product.image_url }}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{{ product.image_url }}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{{ product.image_url }}" class="d-block w-100" alt="...">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
    </div>
    <!-- Product Description -->
    <div class="col-lg-6 col-md-3">
        <h1 class="text-left">{{ product.name }}</h1>
        <div class="m-5">
            {{ product.name }} description...
            {{ product.price }}
        </div>
        <div class="col-12">
          <a href="{{ url_for('cart.add_to_cart', prod_id=product.id) }}" class="btn btn-primary btn-lg w-100">Add to Cart</a>
        </div>
    </div>
</div>
{% if product.category.products|length > 1 %}
<div class="row">
    <h1 class="text-center">Also check out these items in {{ product.category.name.lower() }}</h1>
    {% for p in product.category.products %}
        {% if p.id != product.id %}
            <div class="col-md-4">
                <div class="card">
                    <img src="{{ p.image_url }}" class="card-img-top" alt="{{ p.name }}">
                    <!-- style="width: 300px; height: 337px; object-fit: cover;" -->
                    <div class="card-body">
                      <h5 class="card-title">{{ p.name }}</h5>
                      <p class="card-text">${{ p.price }}</p>
                      <a href="{{ url_for('products.product_info', prod_id=p.id) }}" class="btn btn-primary">More Info</a>
                    </div>
                  </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endif %}

{% endblock %}

project/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center m-5">Edit Profile</h1>
<div class="text-center mb-3">
    {{ user_profile.username }}
</div>
<form action="" method="post">
    {{ form.csrf_token }}
    <div class="form-group d-flex justify-content-center">
        <div class="col-10 col-md-4 col-sm-6 mb-3">
            <fieldset class="">
                {{ form.password.label }}
                {{ form.password(class='form-control', placeholder='Current Password') }}
            </fieldset>
        </div>
    </div>
    <div class="form-group d-flex justify-content-center">
        <div class="col-10 col-md-4 col-sm-6 mb-3">
            <fieldset class="">
                {{ form.new_password.label }}
                {{ form.new_password(class='form-control', placeholder='New Password') }}
            </fieldset>
        </div>
    </div>
    <div class="form-group d-flex justify-content-center">
        <div class="col-10 col-md-4 col-sm-6 mb-3">
            <fieldset class="">
                {{ form.confirm_pass.label }}
                {{ form.confirm_pass(class='form-control', placeholder='Confirm Password') }}
            </fieldset>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="col-10 col-md-4 col-sm-6">
            {{ form.submit(class='btn btn-outline-primary w-100') }}
        </div>
    </div>
</form>
{% endblock %}

project/templates/register.html
{% block title %} <title>Register</title> {% endblock %}
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center m-5">Register Here!</h1>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div class="form-group d-flex justify-content-center">
            <div class="col-10 col-md-4 col-sm-6 mb-3">
                <fieldset class="">
                    {{ form.username.label }}
                    {{ form.username(class='form-control', placeholder='Username') }}
                </fieldset>
            </div>
        </div>
        <div class="form-group d-flex justify-content-center">
            <div class="col-10 col-md-4 col-sm-6 mb-3">
                <fieldset class="">
                    {{ form.email.label }}
                    {{ form.email(class='form-control', placeholder='Email') }}
                </fieldset>
            </div>
        </div>
        <div class="form-group d-flex justify-content-center">
            <div class="col-10 col-md-4 col-sm-6 mb-3">
                <fieldset class="">
                    {{ form.password.label }}
                    {{ form.password(class='form-control', placeholder='Password') }}
                </fieldset>
            </div>
        </div>
        <div class="form-group d-flex justify-content-center">
            <div class="col-10 col-md-4 col-sm-6 mb-3">
                <fieldset class="">
                    {{ form.confirm_pass.label }}
                    {{ form.confirm_pass(class='form-control', placeholder='Confirm Password') }}
                </fieldset>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            <div class="col-10 col-md-4 col-sm-6">
                {{ form.submit(class='btn btn-outline-primary w-100') }}
            </div>
        </div>
    </form>

<div class="row">
    <div class="d-flex justify-content-center mt-4">
        Have an account already? <a href="{{ url_for('auth.login') }}" class="ms-2 me-2">login</a>
    </div>
</div>
{% endblock %}